listener 1883
allow_anonymous true
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Connect/Disconnect nur bei Bedarf (Debug): connection_messages true setzen und Broker mit SIGHUP neu laden
connection_messages false
