"""Adding and removing the optional components of a box.

Card reader, LEDs, buttons, display, media import and announcements are
compose profiles (``COMPOSE_PROFILES`` in ``.env``). Until now the only way to
change that choice after the install was an SSH session and the maintenance
menu of ``install.sh``; this module is what puts it in the WebUI instead.

Three things have to happen for one changed checkbox, and they are the reason
this is not simply a write into ``.env``:

* **Switching off.** Removing a profile does not stop a container that is
  already running - compose only stops *starting* it. The containers of the
  deselected profiles are therefore removed explicitly, with those profiles
  temporarily active again so compose still knows the services.
* **Switching on.** A box installed without the display never pulled that
  image, and the card reader and display need ``/dev/i2c-1``, which only
  exists once I2C is enabled on the host. Both are taken care of here, the
  second one best-effort with a reboot hint when the device node is still
  missing afterwards.
* **Surviving the restart.** ``docker compose up -d`` recreates the backend
  (its ``COMPOSE_PROFILES`` changed), and a future change may well recreate
  this service too. The run therefore goes into a transient systemd unit on
  the host, exactly like the update - see ``update.py`` for the full reasoning.
"""

from __future__ import annotations

import json
import subprocess
from datetime import UTC, datetime
from pathlib import Path

import structlog
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from host_helper.api.routes.deps import (
    _check_api_key,
    _host_root,
    _host_workspace,
    _run_on_host_via_nsenter,
    get_config,
    parse_step_markers,
)
from host_helper.api.routes.update import UPDATE_UNIT

logger = structlog.get_logger(__name__)

router = APIRouter()


# Compose profile -> the service behind it. "media" and "voice" carry a
# different name; everything else is called after its profile.
PROFILE_SERVICES: dict[str, str] = {
    "rfid": "rfid",
    "led": "led",
    "button": "button",
    "display": "display",
    "media": "media-downloader",
    "voice": "tts",
}


# These two talk over I2C and get /dev/i2c-1 mapped in. Without the device node
# the container does not even start, so switching them on has to make sure the
# host has I2C enabled - install.sh does the same at install time.
I2C_PROFILES = frozenset({"rfid", "display"})

I2C_DEVICE = "dev/i2c-1"


# What gets written when nothing at all is selected. An empty value would be
# ambiguous: compose passes COMPOSE_PROFILES= into the backend both for "no
# component chosen" and for a .env that never had the line, and the backend
# reads the second case as "everything installed" (fail-open,
# core/capabilities.py). No service carries this profile, so compose starts
# nothing extra for it - it only makes the empty choice say so out loud.
EMPTY_PROFILE_MARKER = "none"


COMPONENT_UNIT = "minabox-components"


# Part of the contract with the WebUI, which translates them as
# system.components_step_<key>. Do not rename them.
COMPONENT_STEPS = ("stop", "pull", "start", "verify")


COMPONENT_SCRIPT = """#!/bin/sh
# Generated by the host-helper (see host_helper/api/routes/components.py). Do
# not edit by hand - this file is overwritten on every run.
exec >>"{log}" 2>&1
cd "{workspace}" || {{
  echo "Working directory {workspace} not found"
  echo "=== MINABOX-DONE 1"
  exit 1
}}

rc=0
REMOVED="{removed_services}"
ADDED="{added_services}"
BLOCKED="{blocked_services}"

echo "=== MINABOX-STEP 1/4 stop"
# A profile taken out of COMPOSE_PROFILES does not stop a running container -
# it only stops compose from starting it next time. The profiles are handed
# back in here for the length of this one command, otherwise compose no longer
# knows the services it is being asked to remove.
if [ -n "$REMOVED" ]; then
  OFF="{removed_profiles}"
  COMPOSE_PROFILES="$OFF" docker compose rm --stop --force $REMOVED || rc=$?
else
  echo "  (nothing to switch off)"
fi

if [ "$rc" = "0" ]; then
  echo "=== MINABOX-STEP 2/4 pull"
  # A box that never had this component never pulled its image. Not fatal: an
  # image that is already on disk is enough, and a box without internet must
  # still be able to switch a component on.
  if [ -n "$ADDED" ]; then
    docker compose pull $ADDED || echo "(pull not possible - using what is on disk)"
  else
    echo "  (nothing new to download)"
  fi
fi

if [ "$rc" = "0" ]; then
  echo "=== MINABOX-STEP 3/4 start"
  # Without BLOCKED this is a plain "up -d". With it, the services that are
  # still waiting for a reboot are left out - starting them now would fail on
  # the missing device and take the rest of the run down with them.
  if [ -n "$BLOCKED" ]; then
    keep=""
    for s in $(docker compose config --services); do
      skip=0
      for b in $BLOCKED; do
        [ "$s" = "$b" ] && skip=1
      done
      [ "$skip" = "0" ] && keep="$keep $s"
    done
    docker compose up -d $keep || rc=$?
  else
    docker compose up -d || rc=$?
  fi
fi

if [ "$rc" = "0" ]; then
  echo "=== MINABOX-STEP 4/4 verify"
  # --type container on both checks: without it "docker inspect" also matches
  # an *image* of that name, and a leftover "minabox-media-downloader:latest"
  # from an old local build makes a removed container look like it is still
  # there.
  fmt='{{{{ .State.Status }}}}'
  for name in {want_running}; do
    state="$(docker inspect --type container --format "$fmt" \
      "minabox-$name" 2>/dev/null)"
    if [ "$state" = "running" ]; then
      echo "  $name: running"
    else
      echo "  $name: expected running, is ${{state:-absent}}"
      rc=1
    fi
  done
  for name in {want_gone}; do
    if docker inspect --type container "minabox-$name" >/dev/null 2>&1; then
      echo "  $name: still there"
      rc=1
    else
      echo "  $name: removed"
    fi
  done
fi

echo "=== MINABOX-DONE $rc"
"""


class ComponentsBody(BaseModel):
    """The components this box should have, as compose profiles."""

    profiles: list[str]


def _component_paths() -> tuple[Path, Path, Path, str]:
    """(log, script, state file) inside the container, plus the log on the host."""
    cfg = get_config()
    data_path = cfg.data_path.resolve()
    return (
        data_path / "minabox-components.log",
        data_path / "minabox-components.sh",
        data_path / "minabox-components-state.json",
        f"{_host_workspace()}/data/minabox-components.log",
    )


def read_profiles(env_path: Path) -> list[str]:
    """The profiles currently written in .env, in the order this module lists them.

    A missing line reads as "everything" - the same fail-open the backend uses
    (core/capabilities.py): a box whose .env predates the profiles ran every
    component, and nothing should disappear from the UI over a missing line.
    """
    raw: str | None = None
    if env_path.exists():
        try:
            for line in env_path.read_text(
                encoding="utf-8", errors="replace"
            ).splitlines():
                stripped = line.strip()
                if stripped.startswith("COMPOSE_PROFILES="):
                    raw = stripped.split("=", 1)[1].strip().strip('"').strip("'")
        except OSError as e:
            logger.warning("compose_profiles_unreadable", error=str(e))
    if raw is None:
        return list(PROFILE_SERVICES)
    chosen = {p.strip() for p in raw.split(",") if p.strip()}
    return [p for p in PROFILE_SERVICES if p in chosen]


def _write_profiles(env_path: Path, profiles: list[str]) -> None:
    """Set COMPOSE_PROFILES in .env; every other line stays exactly as it is."""
    content = (
        env_path.read_text(encoding="utf-8", errors="replace")
        if env_path.exists()
        else ""
    )
    value = ",".join(profiles) if profiles else EMPTY_PROFILE_MARKER
    new_line = f"COMPOSE_PROFILES={value}"
    lines = content.splitlines()
    for i, line in enumerate(lines):
        if line.strip().startswith("COMPOSE_PROFILES="):
            lines[i] = new_line
            break
    else:
        lines.append(new_line)
    env_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _i2c_present() -> bool:
    """Whether /dev/i2c-1 exists on the host."""
    return (_host_root() / I2C_DEVICE).exists()


def _enable_i2c() -> None:
    """Switch I2C on with raspi-config, the same call install.sh makes.

    Best-effort on purpose: on a box without raspi-config there is nothing to
    do here, and the caller finds out what really counts - whether the device
    node is there - by looking for it.
    """
    try:
        result = _run_on_host_via_nsenter(
            ["raspi-config", "nonint", "do_i2c", "0"], timeout=30
        )
        if result.returncode != 0:
            logger.warning(
                "enable_i2c_failed",
                error=(result.stderr or result.stdout or "").strip()[-300:],
            )
    except (subprocess.SubprocessError, OSError, FileNotFoundError) as e:
        logger.warning("enable_i2c_unavailable", error=str(e))


def _unit_active(unit: str) -> bool:
    try:
        result = _run_on_host_via_nsenter(
            ["systemctl", "is-active", f"{unit}.service"], timeout=10
        )
        return result.stdout.strip() == "active"
    except Exception as e:  # noqa: BLE001 - an unreadable unit is not a failure
        logger.debug("unit_state_failed", unit=unit, error=str(e))
        return False


def _read_state(state_path: Path) -> dict:
    if not state_path.exists():
        return {}
    try:
        loaded = json.loads(state_path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


@router.get("/system/components")
def get_components(_: None = Depends(_check_api_key)) -> dict:
    """The optional components and which of them this box is set up for.

    Reads .env, not the environment of this process: after a change the value
    on disk is the current one, while every container still carries the value
    it was started with.
    """
    profiles = read_profiles(get_config().env_file_path)
    return {
        "components": [
            {"profile": profile, "service": service, "installed": profile in profiles}
            for profile, service in PROFILE_SERVICES.items()
        ],
        "profiles": profiles,
        "busy": _unit_active(COMPONENT_UNIT),
    }


@router.put("/system/components")
def put_components(
    body: ComponentsBody,
    _: None = Depends(_check_api_key),
) -> dict:
    """Set the components of this box and bring the stack to that state.

    Returns as soon as the run has started; the progress comes from
    /system/components/status.

    Nothing is deleted here. A component that is switched off loses its
    container, not its data: card assignments and settings stay where they
    are, and the backend answers a call into an absent component with a 409
    (require_feature), so switching it back on is lossless.
    """
    log_path, script_path, state_path, host_log = _component_paths()
    cfg = get_config()
    env_path = cfg.env_file_path

    unknown = sorted(set(body.profiles) - set(PROFILE_SERVICES))
    if unknown:
        raise HTTPException(
            status_code=400, detail=f"Unknown components: {', '.join(unknown)}"
        )
    # Same order as everywhere else, and without duplicates - the value ends up
    # in .env, where "rfid,rfid" would be readable but silly.
    wanted = [p for p in PROFILE_SERVICES if p in set(body.profiles)]

    if _unit_active(COMPONENT_UNIT):
        raise HTTPException(status_code=409, detail="A change is already running")
    # An update recreates containers too. Two of them at once in the same
    # project directory is a fight nobody wins.
    if _unit_active(UPDATE_UNIT):
        raise HTTPException(status_code=409, detail="An update is running")

    current = read_profiles(env_path)
    added = [p for p in wanted if p not in current]
    removed = [p for p in current if p not in wanted]
    if not added and not removed:
        return {
            "ok": True,
            "changed": False,
            "profiles": wanted,
            "reboot_required": False,
            "blocked": [],
            "steps": list(COMPONENT_STEPS),
        }

    # I2C first: it decides which of the newly selected services can start at
    # all in this run.
    reboot_required = False
    if any(p in I2C_PROFILES for p in added) and not _i2c_present():
        _enable_i2c()
        reboot_required = not _i2c_present()
    blocked = (
        [PROFILE_SERVICES[p] for p in added if p in I2C_PROFILES]
        if reboot_required
        else []
    )

    started_at = datetime.now(UTC).isoformat()
    want_running = [
        PROFILE_SERVICES[p] for p in wanted if PROFILE_SERVICES[p] not in blocked
    ]
    try:
        _write_profiles(env_path, wanted)
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text(
            COMPONENT_SCRIPT.format(
                log=host_log,
                workspace=_host_workspace(),
                removed_profiles=",".join(removed),
                removed_services=" ".join(PROFILE_SERVICES[p] for p in removed),
                added_services=" ".join(
                    PROFILE_SERVICES[p]
                    for p in added
                    if PROFILE_SERVICES[p] not in blocked
                ),
                blocked_services=" ".join(blocked),
                want_running=" ".join(want_running),
                want_gone=" ".join(PROFILE_SERVICES[p] for p in removed),
            ),
            encoding="utf-8",
        )
        script_path.chmod(0o755)
        log_path.write_text(
            f"Components: {','.join(wanted) or '-'}\n", encoding="utf-8"
        )
        state_path.write_text(
            json.dumps(
                {
                    "started_at": started_at,
                    "profiles": wanted,
                    "added": added,
                    "removed": removed,
                    "reboot_required": reboot_required,
                    "blocked": blocked,
                },
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )
    except OSError as e:
        raise HTTPException(
            status_code=503, detail=f"Could not prepare the change: {e}"
        ) from e

    host_script = f"{_host_workspace()}/data/minabox-components.sh"
    try:
        result = _run_on_host_via_nsenter(
            [
                "systemd-run",
                f"--unit={COMPONENT_UNIT}",
                "--collect",
                "--description=Minabox components",
                "/bin/sh",
                host_script,
            ],
            timeout=30,
        )
    except Exception as e:
        raise HTTPException(
            status_code=503, detail=f"Could not start the change: {e}"
        ) from e

    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "systemd-run failed")[-500:]
        raise HTTPException(status_code=503, detail=detail)

    logger.info(
        "components_change_started",
        profiles=wanted,
        added=added,
        removed=removed,
        reboot_required=reboot_required,
    )
    return {
        "ok": True,
        "changed": True,
        "profiles": wanted,
        "reboot_required": reboot_required,
        "blocked": blocked,
        "steps": list(COMPONENT_STEPS),
    }


@router.get("/system/components/status")
def get_components_status(_: None = Depends(_check_api_key)) -> dict:
    """Progress and output of the running or last component change."""
    log_path, _script, state_path, _host_log = _component_paths()

    log_text = ""
    if log_path.exists():
        try:
            lines = log_path.read_text(encoding="utf-8", errors="replace").splitlines()
            if len(lines) > 500:
                lines = lines[-500:]
            log_text = "\n".join(lines)
        except OSError:
            pass

    parsed = parse_step_markers(log_text, len(COMPONENT_STEPS))
    # The unit is the truth about "still running": a run that was killed before
    # writing its closing marker would otherwise count as running forever.
    running = parsed["exit_code"] is None and _unit_active(COMPONENT_UNIT)
    state = _read_state(state_path)

    return {
        "running": running,
        "steps": list(COMPONENT_STEPS),
        "log": log_text,
        "profiles": state.get("profiles") or [],
        "reboot_required": bool(state.get("reboot_required")),
        "blocked": state.get("blocked") or [],
        **parsed,
    }
