"""Updating Minabox itself and the host operating system."""

from __future__ import annotations

import json
import os
import re
import subprocess
import threading
from datetime import UTC, datetime
from pathlib import Path

import structlog
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from host_helper.api.routes.backup import _write_backup_zip
from host_helper.api.routes.deps import (
    _check_api_key,
    _docker,
    _drop_docker_client,
    _host_tool,
    _host_workspace,
    _nsenter_bin,
    _run_on_host_via_nsenter,
    get_config,
)

logger = structlog.get_logger(__name__)

router = APIRouter()


# ── Minabox Update & Version ──────────────────────────────────────────────

# The update runs as a transient systemd unit on the HOST, not as a child of
# this container. Two reasons:
#
#   1. "docker compose up -d" recreates the host-helper as soon as its own
#      image has changed. A child process of this container would die with it,
#      halfway through the update.
#   2. There is no Docker CLI inside the container; the host has one.
#
# Progress is written to the log as markers. That survives any restart of the
# host-helper, because the file lives in the project directory.
#
# The step keys below are part of the contract: the WebUI translates them as
# system.update_step_<key>. Do not rename them.
UPDATE_UNIT = "minabox-update"


UPDATE_STEPS = ("backup", "repo", "pull", "restart", "verify")


# How many pre-update backups to keep. Five is enough to survive an update
# that went wrong without filling up the SD card.
BACKUP_KEEP = 5


# ── Update history ────────────────────────────────────────────────────────
#
# Every run records what was running before it. That file is the whole basis
# of the way back: without it, "revert to the previous version" would be a
# guess, and the only real answer would be an SSH session and an editor in
# .env - on a box that a family uses every day.
#
# It is written before the update starts, not after: if the run dies halfway
# through, the way back is exactly the interesting one.
HISTORY_KEEP = 20


UPDATE_SCRIPT = """#!/bin/sh
# Generated by the host-helper (see host_helper/api/routes.py). Do not edit by
# hand - this file is overwritten on every update.
exec >>"{log}" 2>&1
cd "{workspace}" || {{
  echo "Working directory {workspace} not found"
  echo "=== MINABOX-DONE 1"
  exit 1
}}

rc=0
SERVICES="{services}"

echo "=== MINABOX-STEP 2/5 repo"
# git runs as the owner of the project directory, not as root. Otherwise it
# would leave root-owned files behind in .git and the user could no longer
# work in their own tree.
#
# Deliberately not fatal: a box with local changes, or without access to the
# git remote, must still be able to update its images.
OWNER="$(stat -c %U .)"
if [ -n "$OWNER" ] && [ "$OWNER" != "UNKNOWN" ]; then
  runuser -u "$OWNER" -- git pull --ff-only \
    || echo "(git pull not possible - updating the images anyway)"
else
  echo "(cannot determine the owner of the project directory - skipping git pull)"
fi

echo "=== MINABOX-STEP 3/5 pull"
# An empty service list means all of them - that is the "everything to the
# newest build" path.
docker compose pull $SERVICES || rc=$?

if [ "$rc" = "0" ]; then
  echo "=== MINABOX-STEP 4/5 restart"
  docker compose up -d $SERVICES || rc=$?
fi

if [ "$rc" = "0" ]; then
  echo "=== MINABOX-STEP 5/5 verify"
  # Not just "is running" but "is running the version we asked for": a
  # container compose did not recreate looks healthy while still executing
  # the old build.
  for entry in {expected}; do
    name="${{entry%%=*}}"
    want="${{entry#*=}}"
    got="$(docker inspect --format '{{{{ index .Config.Labels "org.opencontainers.image.version" }}}}' "minabox-$name" 2>/dev/null)"
    if [ "$got" = "$want" ]; then
      echo "  $name: $got"
    else
      echo "  $name: expected $want, running $got"
      rc=1
    fi
  done
fi

echo "=== MINABOX-DONE $rc"
"""


class UpdateTargetsBody(BaseModel):
    """Target version per service. Empty means: everything to the newest build."""

    targets: dict[str, str] | None = None
    backup: bool = True
    #: The database schema version the box runs *before* this update. Passed
    #: in by the backend, which is the only service that knows it, and stored
    #: unread - the backend compares it again when it has to decide whether a
    #: rollback across it is safe. See the history below.
    schema_version: int | None = None
    #: "update" or "rollback". Only ever used to label the history entry.
    kind: str = "update"


def _update_paths() -> tuple[Path, Path, Path, str]:
    """(log, script, state file) inside the container, plus the log path on the host."""
    cfg = get_config()
    data_path = cfg.data_path.resolve()
    host_workspace = _host_workspace()
    return (
        data_path / "minabox-update.log",
        data_path / "minabox-update.sh",
        data_path / "minabox-update-state.json",
        f"{host_workspace}/data/minabox-update.log",
    )


def _service_names() -> list[str]:
    """The services this project knows, derived from the VERSION files on disk."""
    cfg = get_config()
    workspace = cfg.workspace_path.resolve()
    return sorted(
        p.parent.name.removesuffix("-service")
        for p in (workspace / "services").glob("*-service/VERSION")
    )


def _tag_var(service: str) -> str:
    return f"MINABOX_{service.upper().replace('-', '_')}_TAG"


def _running_versions() -> dict[str, str]:
    """The running version per service, read from the container label."""
    versions: dict[str, str] = {}
    try:
        client = _docker()
    except Exception as e:
        _drop_docker_client()
        logger.debug("running_versions_unavailable", error=str(e))
        return versions
    for service in _service_names():
        try:
            container = client.containers.get(f"minabox-{service}")
            version = (container.labels or {}).get("org.opencontainers.image.version")
            if version:
                versions[service] = version
        except Exception:
            continue
    return versions


def _read_env_tags(env_path: Path) -> dict[str, str]:
    """The image tags currently pinned in .env, per service."""
    tags: dict[str, str] = {}
    if not env_path.exists():
        return tags
    try:
        content = env_path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return tags
    wanted = {_tag_var(service): service for service in _service_names()}
    for line in content.splitlines():
        stripped = line.strip()
        if stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        service = wanted.get(key.strip())
        if service and value.strip():
            tags[service] = value.strip()
    return tags


def _write_env_tags(env_path: Path, tags: dict[str, str]) -> None:
    """Set or append the tag lines in .env; everything else stays untouched."""
    content = (
        env_path.read_text(encoding="utf-8", errors="replace")
        if env_path.exists()
        else ""
    )
    lines = content.splitlines()
    for service, version in sorted(tags.items()):
        new_line = f"{_tag_var(service)}={version}"
        prefix = f"{_tag_var(service)}="
        for i, line in enumerate(lines):
            if line.strip().startswith(prefix):
                lines[i] = new_line
                break
        else:
            lines.append(new_line)
    env_path.write_text("\n".join(lines) + ("\n" if lines else ""), encoding="utf-8")


def _prune_backups(backup_dir: Path) -> None:
    files = sorted(
        backup_dir.glob("pre-update-*.zip"), key=lambda p: p.name, reverse=True
    )
    for old in files[BACKUP_KEEP:]:
        try:
            old.unlink()
        except OSError:
            pass


def _history_path() -> Path:
    return get_config().data_path.resolve() / "minabox-update-history.json"


def read_history() -> list[dict]:
    """The recorded runs, newest first. A damaged file reads as no history."""
    path = _history_path()
    if not path.exists():
        return []
    try:
        loaded = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as e:
        logger.debug("update_history_unreadable", error=str(e))
        return []
    if not isinstance(loaded, list):
        return []
    return [entry for entry in loaded if isinstance(entry, dict)]


def append_history(entry: dict) -> None:
    """Record one run. Never fatal - an update must not fail over its diary."""
    path = _history_path()
    entries = [entry, *read_history()][:HISTORY_KEEP]
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(entries, ensure_ascii=False), encoding="utf-8")
    except OSError as e:
        logger.warning("update_history_unwritable", error=str(e))


def _update_unit_active() -> bool:
    try:
        result = _run_on_host_via_nsenter(
            ["systemctl", "is-active", f"{UPDATE_UNIT}.service"], timeout=10
        )
        return result.stdout.strip() == "active"
    except Exception as e:
        logger.debug("update_unit_state_failed", error=str(e))
        return False


def _parse_update_log(text: str) -> dict:
    """Read the current step and the result from the markers in the log."""
    step: int | None = None
    step_count = len(UPDATE_STEPS)
    step_key: str | None = None
    exit_code: int | None = None
    for line in text.splitlines():
        if line.startswith("=== MINABOX-STEP "):
            parts = line.removeprefix("=== MINABOX-STEP ").split()
            if len(parts) >= 2 and "/" in parts[0]:
                current, _, total = parts[0].partition("/")
                if current.isdigit() and total.isdigit():
                    step, step_count = int(current), int(total)
                    step_key = parts[1]
        elif line.startswith("=== MINABOX-DONE "):
            value = line.removeprefix("=== MINABOX-DONE ").strip()
            exit_code = int(value) if value.lstrip("-").isdigit() else -1
    return {
        "step": step,
        "step_count": step_count,
        "step_key": step_key,
        "exit_code": exit_code,
    }


@router.post("/system/update-minabox")
def update_minabox(
    body: UpdateTargetsBody | None = None,
    _: None = Depends(_check_api_key),
) -> dict:
    """Start the update in the background.

    With `targets`, exactly the named services go to exactly the named
    versions, and every other service is pinned to the version it currently
    runs so a targeted update cannot drag anything else along. Without
    `targets`, everything goes to the newest published build.
    """
    log_path, script_path, state_path, host_log = _update_paths()
    host_workspace = _host_workspace()
    cfg = get_config()
    env_path = cfg.env_file_path

    if _update_unit_active():
        raise HTTPException(status_code=409, detail="An update is already running")

    targets = dict((body.targets or {}) if body else {})
    known = set(_service_names())
    unknown = sorted(set(targets) - known)
    if unknown:
        raise HTTPException(
            status_code=400, detail=f"Unknown services: {', '.join(unknown)}"
        )
    for service, version in targets.items():
        if not re.fullmatch(r"[0-9A-Za-z][0-9A-Za-z._-]{0,63}", version or ""):
            raise HTTPException(
                status_code=400, detail=f"Invalid version for {service}"
            )

    running = _running_versions()
    previous = {**running, **_read_env_tags(env_path)}
    started_at = datetime.now(UTC).isoformat()

    log_lines = ["=== MINABOX-STEP 1/5 backup"]
    if body is None or body.backup:
        try:
            backup_dir = cfg.data_path
            backup_dir = backup_dir / "backups"
            backup_dir.mkdir(parents=True, exist_ok=True)
            stamp = datetime.now(UTC).strftime("%Y%m%d-%H%M%S")
            backup_file = backup_dir / f"pre-update-{stamp}.zip"
            _write_backup_zip(backup_file)
            _prune_backups(backup_dir)
            log_lines.append(f"  Backup: data/backups/{backup_file.name}")
        except Exception as e:
            # No backup, no update. Without one the way back would be
            # nothing but hope.
            raise HTTPException(status_code=503, detail=f"Backup failed: {e}") from e
    else:
        log_lines.append("  (skipped)")

    if targets:
        # Pin every other service to what it currently runs. Without that,
        # "compose up -d" would drag them all to latest on the next run and a
        # targeted update would not be one.
        pinned = {**running, **targets}
        services = " ".join(sorted(targets))
        expected = {service: targets[service] for service in targets}
    else:
        pinned = {}
        services = ""
        expected = {}

    try:
        if pinned:
            _write_env_tags(env_path, pinned)
            log_lines.append(
                "  Pinned: " + ", ".join(f"{k}={v}" for k, v in sorted(pinned.items()))
            )
        script_path.parent.mkdir(parents=True, exist_ok=True)
        script_path.write_text(
            UPDATE_SCRIPT.format(
                log=host_log,
                workspace=host_workspace,
                services=services,
                expected=" ".join(f"{k}={v}" for k, v in sorted(expected.items())),
            ),
            encoding="utf-8",
        )
        script_path.chmod(0o755)
        log_path.write_text("\n".join(log_lines) + "\n", encoding="utf-8")
        state_path.write_text(
            json.dumps(
                {
                    "started_at": started_at,
                    "previous": previous,
                    "targets": targets,
                },
                ensure_ascii=False,
            ),
            encoding="utf-8",
        )
    except OSError as e:
        raise HTTPException(
            status_code=503, detail=f"Could not prepare the update: {e}"
        ) from e

    host_script = f"{host_workspace}/data/minabox-update.sh"
    try:
        result = _run_on_host_via_nsenter(
            [
                "systemd-run",
                f"--unit={UPDATE_UNIT}",
                "--collect",
                "--description=Minabox update",
                "/bin/sh",
                host_script,
            ],
            timeout=30,
        )
    except Exception as e:
        raise HTTPException(
            status_code=503, detail=f"Could not start the update: {e}"
        ) from e

    if result.returncode != 0:
        detail = (result.stderr or result.stdout or "systemd-run failed")[-500:]
        raise HTTPException(status_code=503, detail=detail)

    # Only now, with the run actually started: a rejected systemd-run leaves
    # the box exactly where it was, and an entry for it would offer a way back
    # from a step that never happened.
    append_history(
        {
            "id": started_at,
            "started_at": started_at,
            "kind": "rollback" if (body and body.kind == "rollback") else "update",
            "previous": previous,
            "targets": targets,
            "schema_version": body.schema_version if body else None,
        }
    )

    logger.info("update_minabox_started", targets=targets or "all")
    return {"ok": True, "message": "Update started", "steps": list(UPDATE_STEPS)}


@router.get("/system/update-history")
def update_history(_: None = Depends(_check_api_key)) -> dict:
    """The recorded runs plus what is running right now.

    Deliberately raw: which of these tags may be gone back to is a question
    about the database schema, and only the backend knows that. This route
    hands over the facts, the backend draws the conclusion.
    """
    return {"entries": read_history(), "running": _running_versions()}


@router.get("/system/update-minabox/status")
def update_minabox_status(_: None = Depends(_check_api_key)) -> dict:
    """Progress and output of the running or last update."""
    log_path, _script, state_path, _host_log = _update_paths()

    log_text = ""
    if log_path.exists():
        try:
            lines = log_path.read_text(encoding="utf-8", errors="replace").splitlines()
            if len(lines) > 2000:
                lines = lines[-2000:]
            log_text = "\n".join(lines)
        except OSError:
            pass

    parsed = _parse_update_log(log_text)
    # The unit is the truth about "still running". Without asking it, a run
    # that was killed before writing its closing marker would count as running
    # forever.
    running = parsed["exit_code"] is None and _update_unit_active()

    state: dict = {}
    if state_path.exists():
        try:
            state = json.loads(state_path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            state = {}

    # "previous" stays in the state file: for a support request, "what was
    # running before" is the first question. It is not offered as an action -
    # stepping back to an older build can leave data behind that the older
    # build cannot read.
    return {
        "running": running,
        "steps": list(UPDATE_STEPS),
        "log": log_text,
        "targets": state.get("targets") or {},
        **parsed,
    }


@router.get("/system/version")
def get_version(_: None = Depends(_check_api_key)) -> dict:
    """Return the commit the project directory sits on.

    `update_available` is always False here. Whether a newer *image* exists is
    a different question from whether the git worktree is behind origin/main -
    a box can be git-current and still run last week's containers. The backend
    answers it properly against the registry (core/update_check.py); this route
    keeps the field only so its response shape stays stable.
    """
    cfg = get_config()
    workspace = cfg.workspace_path.resolve()
    current_commit: str | None = None
    ref_file = workspace / ".git/refs/heads/main"
    if ref_file.exists():
        try:
            current_commit = ref_file.read_text(encoding="utf-8").strip()[:12]
        except OSError:
            pass
    if not current_commit and (workspace / ".git/HEAD").exists():
        try:
            head = (workspace / ".git/HEAD").read_text(encoding="utf-8").strip()
            if head.startswith("ref: "):
                ref_path = workspace / ".git" / head[5:].strip()
                if ref_path.exists():
                    current_commit = ref_path.read_text(encoding="utf-8").strip()[:12]
        except OSError:
            pass
    return {
        "current_version": current_commit or "unknown",
        "current_commit": current_commit,
        "update_available": False,
    }


def _os_update_running(pid_path: Path) -> bool:
    """True while the apt process from an earlier call is still alive.

    The container shares the host PID namespace (pid: host in compose), so the
    recorded PID is visible here and signal 0 is enough to ask about it.
    """
    if not pid_path.exists():
        return False
    try:
        os.kill(int(pid_path.read_text(encoding="utf-8").strip()), 0)
    except (OSError, ValueError):
        return False
    return True


def _os_update_wait_and_finish(
    proc: subprocess.Popen, log_path: Path, pid_path: Path
) -> None:
    """Wait for apt, append its exit code to the log, drop the PID file."""
    try:
        proc.wait(timeout=3600)
        code = proc.returncode
    except subprocess.TimeoutExpired:
        code = -1
    try:
        with open(log_path, "a", encoding="utf-8", errors="replace") as f:
            f.write(f"\n--- Exit code: {code} ---\n")
    except OSError:
        pass
    try:
        pid_path.unlink(missing_ok=True)
    except OSError:
        pass


@router.post("/system/update-os")
def update_os(_: None = Depends(_check_api_key)) -> dict:
    """Start the host OS upgrade in the background and return immediately."""
    cfg = get_config()
    data_path = cfg.data_path.resolve()
    log_path = data_path / "os-update.log"
    pid_path = data_path / "os-update.pid"
    # Two apt processes only ever fight over the dpkg lock, and the second one
    # would overwrite the log the first is still writing.
    if _os_update_running(pid_path):
        raise HTTPException(status_code=409, detail="An OS update is already running")
    if _host_tool("usr/bin/apt-get") is None:
        raise HTTPException(status_code=503, detail="apt-get not found on host")
    try:
        nsenter = _nsenter_bin()
    except FileNotFoundError as e:
        raise HTTPException(
            status_code=503, detail="nsenter not available on host"
        ) from e
    cmd = [
        # /bin/sh is resolved in the host's mount namespace, after nsenter.
        str(nsenter),
        "-t",
        "1",
        "-n",
        "-m",
        "--",
        "/bin/sh",
        "-c",
        "export DEBIAN_FRONTEND=noninteractive PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin; "
        "apt-get update -qq && apt-get upgrade -y",
    ]
    try:
        data_path.mkdir(parents=True, exist_ok=True)
        with open(log_path, "w", encoding="utf-8") as log_file:
            proc = subprocess.Popen(
                cmd,
                stdout=log_file,
                stderr=subprocess.STDOUT,
                start_new_session=True,
            )
        pid_path.write_text(str(proc.pid), encoding="utf-8")
        t = threading.Thread(
            target=_os_update_wait_and_finish,
            args=(proc, log_path, pid_path),
            daemon=True,
        )
        t.start()
        logger.info("update_os_started", pid=proc.pid)
        return {
            "ok": True,
            "message": "OS update started in background (may take several minutes)",
        }
    except OSError as e:
        raise HTTPException(
            status_code=503, detail=f"Host OS update failed: {e}"
        ) from e


@router.get("/system/update-os/log")
def update_os_log(_: None = Depends(_check_api_key)) -> dict:
    """Return current OS update log and whether the process is still running."""
    cfg = get_config()
    data_path = cfg.data_path.resolve()
    log_path = data_path / "os-update.log"
    pid_path = data_path / "os-update.pid"
    running = _os_update_running(pid_path)
    log_text = ""
    if log_path.exists():
        try:
            raw = log_path.read_text(encoding="utf-8", errors="replace")
            lines = raw.splitlines()
            if len(lines) > 2000:
                lines = lines[-2000:]
            log_text = "\n".join(lines)
        except OSError:
            pass
    return {"running": running, "log": log_text}
